### ISSUE TITLE
lastest rates returning a list, to_currency expects a Map

### ISSUE THREAD

**Issue by ratbag98** [kipcole9/money#33]
```
iex(6)> Money.to_currency Money.new(:GBP,1000), :USD
** (BadMapError) expected a map, got: [XAG: #Decimal<0.05915423>, GTQ: #Decimal<7.353912>, JEP: #Decimal<0.75843>, MOP: #Decimal<8.039316>, DJF: #Decimal<178.77>, UAH: #Decimal<26.58477>, MRO: #Decimal<355.5>, CLP: #Decimal<630.535>, BHD: #Decimal<0.3772>, SHP: #Decimal<0.75843>, NZD: #Decimal<1.436213>, KZT: #Decimal<335.93>, SRD: #Decimal<7.448>, CZK: #Decimal<21.818708>, PYG:  #Decimal<34264.946723>, ...]
    (elixir) lib/map.ex:380: Map.take/2
    (ex_money) lib/money.ex:849: Money.get_rate/2
    (ex_money) lib/money.ex:760: Money.to_currency/3

iex(6)> Money.ExchangeRates.latest_rates
{:ok,
 [XAG: #Decimal<0.05915423>, GTQ: #Decimal<7.353912>, JEP: #Decimal<0.75843>,
  MOP: #Decimal<8.039316>, DJF: #Decimal<178.77>, UAH: #Decimal<26.58477>,
   ...]}

iex(7)> {:ok, rates_list} = Money.ExchangeRates.latest_rates
{:ok,
 [XAG: #Decimal<0.05915423>, GTQ: #Decimal<7.353912>, JEP: #Decimal<0.75843>,
  MOP: #Decimal<8.039316>, DJF: #Decimal<178.77>, UAH: #Decimal<26.58477>,
   ...]}

iex(8)> Money.to_currency Money.new(:GBP,1000), :USD, Enum.into(rates_list, %{})
{:ok, #Money<:USD, 1318.513244465540656355893095>}
```

Obviously easily fixed on 'our' side, but at the very least it's a divergence from the documentation and an irritation.

```
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:10] [hipe] [kernel-poll:false]
...
Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)
```

```
"ex_money": {:hex, :ex_money, "0.6.1", "31d6b572ae0aeec9d2b304df14fc2776c2f75b2e42625e5fe21e0c8851fb3ec8", [:mix], [{:decimal, "~> 1.4", [hex: :decimal, repo: "hexpm", optional: false]}, {:ecto, "~> 2.1", [hex: :ecto, repo: "hexpm", optional: true]}, {:ex_cldr, "~> 0.7.0", [hex: :ex_cldr, repo: "hexpm", optional: false]}, {:ex_cldr_numbers, "~> 0.1.0", [hex: :ex_cldr_numbers, repo: "hexpm", optional: false]}], "hexpm"},
 ```

```
config :ex_money,
  exchange_rate_service: false,
  exchange_rates_retrieve_every: String.to_integer(System.get_env("RETRIEVE_EVERY") || "86400000"),
  open_exchange_rates_app_id: System.get_env("OPEN_EXCHANGE_RATES_APP_ID") || ""
```

(service started in application supervisor since I want to store rates in the database ready to do exciting conversions)

**Comment by kipcole9** [comment]
Thanks for the bug report.  Fixed in master and ex_money version 0.6.2 will be on hex in a few minutes.
