### ISSUE TITLE
Unable to use Jason

### ISSUE THREAD

**Issue by oyeb** [kipcole9/money#71]
I'm trying to encode a `Money.t` struct into JSON (via `jason`) but Jason complains that the `Jason.Encoder` protocol is not implemented for `Money.t`.

# Steps to reproduce
Make a new mix project, add `ex_money` and `jason` in deps:
```elixir
# mix.exs
  defp deps do
    [
      {:ex_money, "~> 2.5.0"},
      {:jason, "~> 1.0"}
    ]
  end
```
Drop this in the config:
```elixir
# config/config.exs
config :ex_money, json_library: Jason
```
Open an IEx shell and,
```elixir
iex(1)> Application.get_all_env :ex_money
[json_library: Jason, included_applications: []]
iex(2)> Cldr.Config.json_library()       
Jason
iex(3)> Jason.encode Money.new(0, :USD)  
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for #Money<:USD, 0>, Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:

    @derive {Jason.Encoder, only: [....]}
    defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:

    @derive Jason.Encoder
    defstruct ...

Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:

    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
    Protocol.derive(Jason.ENcoder, NameOfTheStruct)
. This protocol is implemented for: Any, Atom, BitString, Cldr.LanguageTag, Date, DateTime, Decimal, Float, Integer, Jason.Fragment, List, Map, NaiveDateTime, Time
    (jason) lib/encoder.ex:100: Jason.Encoder.Any.encode/2
    (jason) lib/encode.ex:35: Jason.Encode.encode/2
    (jason) lib/jason.ex:93: Jason.encode/2
```

**Comment by kipcole9** [comment]
Pushed [ex_money version 2.6.0](https://hex.pm/packages/ex_money) with adds protocol derivation for `Jason` and `Poison` with tests.  Thanks for the issue.

**Comment by kipcole9** [comment]
Just noting the obvious:

1. There is no way to automatically decode to the `Money.t` struct
2. The `amount` in the encoded json is a `String.t` in order to preserve precision
